### ISSUE TITLE
Try to get JavaScript generator working

### ISSUE THREAD

**Issue by dsmic** [renatahodovan/grammarinator#18]
Using the antlr grammar I tried to set it up: The grammarinator-process generates references to JavaScriptBaseLexer class:

Any help would be great:)

```
grammarinator-process ../grammars-v4/javascript/javascript/JavaScriptLexer.g4 ../grammars-v4/javascript/javascript/JavaScriptParser.g4 -o testout

grammarinator-generate -l testout/JavaScriptUnlexer.py -p testout/JavaScriptUnparser.py -r htmlDocument -o examples/tests/test_%d.js -n 100 -d 20
Traceback (most recent call last):
  File "/home/detlef/tmp/fuzz/venv/bin/grammarinator-generate", line 11, in <module>
    load_entry_point('grammarinator==19.3+15.g6f43afe.d20200213', 'console_scripts', 'grammarinator-generate')()
  File "/home/detlef/tmp/fuzz/venv/lib/python3.5/site-packages/grammarinator-19.3+15.g6f43afe.d20200213-py3.5.egg/grammarinator/generate.py", line 293, in execute
    cleanup=False, encoding=args.encoding) as generator:
  File "/home/detlef/tmp/fuzz/venv/lib/python3.5/site-packages/grammarinator-19.3+15.g6f43afe.d20200213-py3.5.egg/grammarinator/generate.py", line 69, in __init__
    self.unlexer_cls = import_entity('.'.join([unlexer, unlexer]))
  File "/home/detlef/tmp/fuzz/venv/lib/python3.5/site-packages/grammarinator-19.3+15.g6f43afe.d20200213-py3.5.egg/grammarinator/generate.py", line 57, in import_entity
    return getattr(importlib.import_module('.'.join(steps[0:-1])), steps[-1])
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "testout/JavaScriptUnlexer.py", line 10, in <module>
    from JavaScriptBaseLexer import JavaScriptBaseLexer
ImportError: No module named 'JavaScriptBaseLexer'

```

**Comment by renatahodovan** [comment]
The JavaScript lexer grammar uses a custom super class, implemented in the JavaScriptBaseLexer.py file. However, this module contains instructions for format **recognition** and not for generation (obviously). Hence, either you remove the superClass option from the lexer ([this line](https://github.com/antlr/grammars-v4/blob/master/javascript/javascript/JavaScriptLexer.g4#L35)) or - if you need a generator super class for the unlexer then - after adapting the base class implementation to the generator - copy that file next to the generated unlexer file.

One more note. Your generator command isn't correct: the JavaScript grammar doesn't define the `htmlDocument` rule, instead you should use `program` (or any other rule defined by the grammars).

**Comment by dsmic** [comment]
Thanks a lot. I had to remove some "this." references from the Unlexer and Unparser and at least it is producing code (more or less :).

**Comment by renatahodovan** [comment]
Yeah. The Python backend is not implemented in grammars-v4 for JavaScript yet. Hence, if you use the grammar from the root directory, then the inline code snippets are in Java. However, most probably you won't need those snippets/actions at all, since they are for parsing purposes and not for generation. To avoid manually removing them, you can run grammarinator-process  with the `--no-actions` cli option.

**Comment by akosthekiss** [comment]
Closing this issue as almost one and a half year has passed since the original report, and the issue seems to have been discussed and solved. However, if the problem still stands, feel free to re-open this issue (or open a new one).
