### ISSUE TITLE
grammarinator-process triggers ValueError: Unicode properties (\p{...}) are not supported 

### ISSUE THREAD

**Issue by jeffreylovitz** [renatahodovan/grammarinator#27]
Using the current HEAD of master and running the  command:
```
grammarinator-process --no-actions Cypher.g4 --pep8 --encoding utf-8
```
After a few seconds, the following traceback is generated:
```
Traceback (most recent call last):
  File "/home/tower-linux/.local/bin/grammarinator-process", line 11, in <module>
    load_entry_point('grammarinator==19.3+53.gbfde275', 'console_scripts', 'grammarinator-process')()
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 748, in execute
    FuzzerFactory(args.language, args.out, args.antlr).generate_fuzzer(args.grammar, options=options, encoding=args.encoding, lib_dir=args.lib, actions=args.actions, pep8=args.pep8)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 656, in generate_fuzzer
    graph = build_graph(self.antlr_parser_cls, actions, lexer_root, parser_root)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 600, in build_graph
    build_rules(root)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 582, in build_rules
    build_rule(*rule_args)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 527, in build_rule
    build_expr(node, rule.id)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 522, in build_expr
    build_expr(child, parent_id)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 398, in build_expr
    build_expr(children[0], parent_id)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 426, in build_expr
    build_expr(child, parent_id)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 445, in build_expr
    build_expr(node.children[0], parent_id)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 497, in build_expr
    ranges = lexer_charset_interval(str(node.LEXER_CHAR_SET())[1:-1])
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 362, in lexer_charset_interval
    codepoint, offset = lexer_charset_char(s, offset)
  File "/home/tower-linux/.local/lib/python3.8/site-packages/grammarinator-19.3+53.gbfde275-py3.8.egg/grammarinator/process.py", line 330, in lexer_charset_char
    raise ValueError('Unicode properties (\\p{...}) are not supported')
ValueError: Unicode properties (\p{...}) are not supported
```

Cypher.g4 can be found here - https://gist.github.com/jeffreylovitz/25f6ed569e3fc474e1d360fff9407446

**Comment by akosthekiss** [comment]
@jeffreylovitz Thanks for the report. The error message is just about right: the property syntax (`\p{...}`) of ANTLR4 is not supported by Grammarinator at the moment. Unfortunately, unicode property support is very light in Python, which makes it very hard and error-prone to implement this feature in pure Python (or without additional external dependencies).

As a (quite manual labor intensive) workaround, all `[\p{...}]`s can be rewritten to `[x-y]` character ranges. But that means that the grammar has to be edited, plus puts the burden of getting the ranges right on the user, of course.

**Comment by jeffreylovitz** [comment]
@akosthekiss Thanks for the clarification! I've modified my grammar accordingly, and will close this issue now.
