### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9204

### ISSUE THREAD

**Issue by marcospassos** [renatahodovan/grammarinator#3]
We are facing the following error trying to run the command line tool on a Mac 10.12.5, using Python 3.6 (all files are encoded in UTF8):

```
grammarinator-process Lexer.g4 Parser.g4 -o output/
Traceback (most recent call last):
  File "/usr/local/bin/grammarinator-process", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.6/site-packages/grammarinator/process.py", line 488, in execute
    FuzzerFactory(args.out, args.antlr).generate_fuzzer(args.grammars, args.actions, args.out, args.pep8)
  File "/usr/local/lib/python3.6/site-packages/grammarinator/process.py", line 403, in generate_fuzzer
    root, grammar_parser = self.parse(grammar)
  File "/usr/local/lib/python3.6/site-packages/grammarinator/process.py", line 447, in parse
    current_root, current_parser = self.parse_single(grammar)
  File "/usr/local/lib/python3.6/site-packages/grammarinator/process.py", line 435, in parse_single
    token_stream = CommonTokenStream(self.lexer(FileStream(grammar)))
  File "/usr/local/lib/python3.6/site-packages/antlr4/FileStream.py", line 20, in __init__
    super().__init__(self.readDataFrom(fileName, encoding))
  File "/usr/local/lib/python3.6/site-packages/antlr4/FileStream.py", line 27, in readDataFrom
    return codecs.decode(bytes, encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9204: ordinal not in range(128)
```

**Comment by renatahodovan** [comment]
@marcospassos Which version are you using? A similar problem has been fixed in https://github.com/renatahodovan/grammarinator/commit/32ac3423390dfe6426e5c1248af0e6c168b92b3e (already in the master, but not published to PyPI as a release yet).

**Comment by marcospassos** [comment]
I'm using 17.5.

**Comment by marcospassos** [comment]
I can confirm it fixes the issue. Thank you!
