### ISSUE TITLE
ModuleNotFoundError: No module named 'grammarinator.parser.ANTLRv4Lexer'

### ISSUE THREAD

**Issue by CityOfLight77** [renatahodovan/grammarinator#34]
I got error when running grammarinator-process. I'm using latest grammarinator `grammarinator-19.3.post79+g820a01a.d20210726`. I installed grammarinator with `pip3 install .`
I'm using mac 10.14 with python 3.9.6

```sh
Traceback (most recent call last):
  File "/usr/local/bin/grammarinator-process", line 5, in <module>
    from grammarinator.process import execute
  File "/usr/local/lib/python3.9/site-packages/grammarinator/__init__.py", line 11, in <module>
    from .process import FuzzerFactory
  File "/usr/local/lib/python3.9/site-packages/grammarinator/process.py", line 29, in <module>
    from .parser import ANTLRv4Lexer, ANTLRv4Parser
  File "/usr/local/lib/python3.9/site-packages/grammarinator/parser/__init__.py", line 8, in <module>
    from .ANTLRv4Lexer import ANTLRv4Lexer
ModuleNotFoundError: No module named 'grammarinator.parser.ANTLRv4Lexer'
```

**Comment by akosthekiss** [comment]
I tried to reproduce the error, but had no success.

```
$ sw_vers 
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

$ uname -rms
Darwin 20.5.0 x86_64

$ git rev-parse --short master
820a01a

$ tox
...
  py: commands succeeded
  lint: commands succeeded
  build: commands succeeded
  congratulations :)

$ virtualenv -p python3 venv
created virtual environment CPython3.7.6.final.0-64 in 580ms
...

$ source venv/bin/activate

(venv) $ pip install --upgrade pip setuptools wheel
...
Successfully installed pip-21.2.1 setuptools-57.4.0 wheel-0.36.2

(venv) $ pip install .
...
Successfully installed MarkupSafe-2.0.1 antlerinator-1!1.1.0 antlr4-python3-runtime-4.9.2 autopep8-1.5.7 grammarinator-19.3.post79+g820a01a inators-1.0.0 jinja2-3.0.1 pycodestyle-2.7.0 toml-0.10.2

(venv) $ grammarinator-process --version
grammarinator-process 19.3.post79+g820a01a
```

Could you please try the steps above? Most importantly:
- Does running `tox` pass OK for you?
- Do you have latest pip and setuptools installed? (Possibly in a virtual environment.)
- From the version string, I see that you have local changes in your repository. Do you also see the error without those changes?

**Comment by akosthekiss** [comment]
For the records: I've performed the same steps on py39 with the same result.

```
$ virtualenv -p python3.9 venv39
created virtual environment CPython3.9.6.final.0-64 in 483ms
...

$ source venv39/bin/activate

(venv39) $ pip install --upgrade pip setuptools wheel
...
Successfully installed pip-21.2.1 setuptools-57.4.0

(venv39) $ pip install .
...
Successfully installed MarkupSafe-2.0.1 antlerinator-1!1.1.0 antlr4-python3-runtime-4.9.2 autopep8-1.5.7 grammarinator-19.3.post79+g820a01a inators-1.0.0 jinja2-3.0.1 pycodestyle-2.7.0 toml-0.10.2

(venv39) $ grammarinator-process --version
grammarinator-process 19.3.post79+g820a01a
```

**Comment by akosthekiss** [comment]
@CityOfLight77 Do you still see the error? (And/or do you have feedback on the questions posted above?)

**Comment by guillaumesalagnac** [comment]
google sent me here, I had the same `ModuleNotFoundError: No module named 'grammarinator.parser.ANTLRv4Lexer'`.

What seems to cause the problem is forgetting the step with `pip install --upgrade pip setuptools wheel`. But after I ran this command, and did the `pip install .` once more, the exception went away.

**Comment by akosthekiss** [comment]
@guillaumesalagnac Thanks for the feedback. It's great that you made it work. I'll assume that this was the original problem as well and close this issue as solved.
