### ISSUE TITLE
Fresh install on Ubuntu gives SyntaxError

### ISSUE THREAD

**Issue by dharmeshkakadia** [renatahodovan/grammarinator#9]
uname -a
Linux hn0-sparkd 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

sudo grammarinator-process examples/grammars/HTMLLexer.g4 examples/grammars/HTMLParser.g4 -o examples/fuzzer/
Traceback (most recent call last):
  File "/usr/local/bin/grammarinator-process", line 11, in <module>
    load_entry_point('grammarinator==17.7.post0', 'console_scripts', 'grammarinator-process')()
  File "/home/sshuser/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sshuser/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/home/sshuser/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2422, in load
    return self.resolve()
  File "/home/sshuser/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/grammarinator-17.7.post0-py2.7.egg/grammarinator/__init__.py", line 8, in <module>
    from . import runtime
  File "/usr/local/lib/python2.7/dist-packages/grammarinator-17.7.post0-py2.7.egg/grammarinator/runtime/__init__.py", line 8, in <module>
    from .grammarinator import depthcontrol, Grammarinator, multirange_diff, printable_ascii_ranges, printable_unicode_ranges
  File "/usr/local/lib/python2.7/dist-packages/grammarinator-17.7.post0-py2.7.egg/grammarinator/runtime/grammarinator.py", line 71
    def __init__(self, *, max_cnt=8000):
                        ^
SyntaxError: invalid syntax

**Comment by renatahodovan** [comment]
@dharmeshkakadia: grammarinator is supported from Python3.4 and up (but from the log it seems that you are using Python2.7 which doesn't support keyword-only arguments).

**Comment by dharmeshkakadia** [comment]
Thanks @renatahodovan ! Sorry, I missed that in the readme.
